project:
  type: website
  execute-dir: project

website:
  title: "First Steps"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "floating"
    collapse-level: 1
    contents:
      - href: index.qmd
        text: "Overview"
      - section: tutorials/basic_commands/index.qmd
        text: "Basic Commands"
        contents:
        - href: tutorials/basic_commands/fundamentals.qmd
        - href: tutorials/basic_commands/mathematical_operators.qmd
        - href: tutorials/basic_commands/logical_comparisons.qmd
        - href: tutorials/basic_commands/environments.qmd
        - href: quizzes/basic_commands/index.qmd
          text: "Knowledge Quiz"
      - section: tutorials/functions/index.qmd
        text: "Functions"
        contents:
          - href: tutorials/functions/functions.qmd
          - href: quizzes/functions/index.qmd
            text: "Knoweldge Quiz"
      - section: tutorials/packages/index.qmd
        text: "Packages"
        contents:
          - href: tutorials/packages/installing.qmd
          - href: tutorials/packages/loading.qmd
          - href: quizzes/packages/index.qmd
            text: "Knowledge Quiz"
      - section: tutorials/help/index.qmd
        text: "Documentation"
        contents:
          - href: tutorials/help/sections.qmd
          - href: tutorials/help/access.qmd
          - href: tutorials/help/default_arguments.qmd
          - href: quizzes/help/index.qmd
            text: "Knowledge Quiz"
      - href: tutorials/99_finish.qmd
        text: "Conclusion"

format:
  html:
    theme: cosmo
    css:
      - html/custom.scss
      - html/styles.css
      - html/webex.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    include-after-body: 
      - text: |
          # <script src="/js/progressive-reveal.js"></script>
          <script src="/js/bootstrapify.js"></script>
          <script src="/js/webex.js"></script>

engine: knitr

knitr:
  opts_chunk:
    message: false
    warning: false
    fig-align: center

webr:
  channel-type: "post-message"
  autoload-packages: false

custom-callout:
  practice:
    title: "Practice"
    icon-symbol: "fa-gears"
    color: "green"
  # quiz:
  #   title: "Knowledge Quiz"
  #   icon-symbol: "fa-mortar-board"
  #   color: "violet"
  reading:
    title: "Reading"
    icon-symbol: "fa-book-open"
    color: "violet"
  adv_reading:
    title: "Advanced Reading"
    icon-symbol: "fa-book-open"
    color: "red"
  link:
    title: "External Resources"
    icon-symbol: "fa-link"
    color: "orange"

filters:
  - webr
  - custom-callout
