project:
  type: website
  execute-dir: project

website:
  title: "First Steps"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css:
      - html/custom.scss
      - html/styles.css
    toc: true

webr:
  channel-type: "post-message"

custom-callout:
  practice:
    title: "Practice"
    icon-symbol: "fa-gears"
    color: "green"
  quiz:
    title: "Knowledge Quiz"
    icon-symbol: "fa-mortar-board"
    color: "violet"

engine: knitr

filters:
  - webr
  - custom-callout

